{% set name = "typedpy" %}
{% set version = "0.51" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/loyada/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cccde3cf292f85289d9cbed12fa5a95285d895f4be6fcc3b01cf9fcd1b586c3b
  patches:
    - setup_py.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - typedpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/typedpy/
  summary: Type-safe Python
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CJ-Wright
    - loyada
