{% set name = "typedpy" %}
{% set version = "2.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/loyada/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 2c6b9435a7e5b6caf16b23195d2fe9e9edba2f15e2a0373417bfeaed253451f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - typedpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/typedpy/
  summary: Type-safe Python
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CJ-Wright
    - loyada
