{% set name = "typedpy" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/loyada/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: bf567205c02aa7a974871faaa2ee056f040d464f2860778874c4789b2b14ac81

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - typedpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/typedpy/
  summary: Type-safe Python
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CJ-Wright
    - loyada
