{% set name = "typedpy" %}
{% set version = "1.24" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/loyada/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5bf5ef99803a1ff701d7d866948e6cbfd9154d6c3b05421f2a29d3d4ad46fa45
  patches:
    - setup_py.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - typedpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/typedpy/
  summary: Type-safe Python
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CJ-Wright
    - loyada
