{% set name = "typedpy" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/loyada/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b5212fcb5407131c694f09f538aaa8bc9365a0063bdbbb5eddd62923f9401a58

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - typedpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/typedpy/
  summary: Type-safe Python
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CJ-Wright
    - loyada
